import { DishData } from '../App';
import { ApiOrder } from '../api/orders';
import { MappedReserve } from '../screens/ReservesScreen';
import { RestaurantInfo } from '../api/restaurant';

// ← ЗАМЕНИ НА РЕАЛЬНЫЙ ДЕМО-НОМЕР когда скажешь
export const DEMO_PHONE = '+74950000001';
export const DEMO_CODE  = '0000';

export const DEMO_RESTAURANT_INFO: RestaurantInfo = {
  name: 'PrestigeCoffee',
  address: 'г. Алматы, ул. Абая, 10',
  phone: '+77771234567',
  isTemporarilyClosed: false,
  deliveryFeeAmount: 800,
  cashbackPercent: 10,
  serviceChargePercent: 12.5,
  workingHours: {
    mon: { open: '09:00', close: '02:00' },
    tue: { open: '09:00', close: '02:00' },
    wed: { open: '09:00', close: '02:00' },
    thu: { open: '09:00', close: '02:00' },
    fri: { open: '09:00', close: '02:00' },
    sat: { open: '09:00', close: '02:00' },
    sun: { open: '09:00', close: '02:00' },
  },
  timezone: 'Asia/Almaty',
};

export const DEMO_LOYALTY_BALANCE = 1250;

const _now = new Date().toISOString();
const _yesterday = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
const _threeDaysAgo = new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString();

export const DEMO_ACTIVE_ORDERS: ApiOrder[] = [
  {
    id: 'demo-active-1',
    iikoNumber: 101,
    orderType: 'DELIVERY',
    status: 'IN_PROGRESS',
    paymentType: 'SCARD',
    paymentStatus: 'PAID',
    totalAmount: '6290',
    deliveryFee: '800',
    promoDiscount: null,
    bonusesSpent: null,
    bonusesEarned: null,
    items: [
      { productId: 'd1', name: 'Маргарита', amount: 1, price: 3500 },
      { productId: 'd2', name: 'Кола 0.5л', amount: 2, price: 995 },
      { productId: 'd3', name: 'Греческий', amount: 1, price: 1800 },
    ],
    deliveryAddress: JSON.stringify({ streetName: 'ул. Абая', house: '10' }),
    createdAt: _now,
    updatedAt: _now,
  },
];

export const DEMO_ORDERS: ApiOrder[] = [
  ...DEMO_ACTIVE_ORDERS,
  {
    id: 'demo-past-1',
    iikoNumber: 98,
    orderType: 'DELIVERY',
    status: 'DELIVERED',
    paymentType: 'SCARD',
    paymentStatus: 'PAID',
    totalAmount: '4590',
    deliveryFee: '800',
    promoDiscount: null,
    bonusesSpent: null,
    bonusesEarned: null,
    items: [
      { productId: 'd4', name: 'Салат Цезарь', amount: 1, price: 2600 },
      { productId: 'd5', name: 'Том Ям', amount: 1, price: 1990 },
    ],
    deliveryAddress: JSON.stringify({ streetName: 'пр. Достык', house: '5' }),
    createdAt: _yesterday,
    updatedAt: _yesterday,
  },
  {
    id: 'demo-past-2',
    iikoNumber: 95,
    orderType: 'PICKUP',
    status: 'DELIVERED',
    paymentType: 'SCASH',
    paymentStatus: 'PAID',
    totalAmount: '3200',
    deliveryFee: null,
    promoDiscount: null,
    bonusesSpent: null,
    bonusesEarned: null,
    items: [
      { productId: 'd6', name: 'Комбо Сет №1', amount: 1, price: 3200 },
    ],
    deliveryAddress: null,
    createdAt: _threeDaysAgo,
    updatedAt: _threeDaysAgo,
  },
];

export const DEMO_RESERVES: MappedReserve[] = [
  {
    id: 'demo-res-1',
    place: '4',
    sectionName: 'Основной зал',
    date: '20.06.2026',
    time: '19:00',
    guests: 4,
    status: 'Ожидается',
    active: true,
    isCancelled: false,
    bookType: 'table',
    comment: 'Столик у окна',
  },
  {
    id: 'demo-res-2',
    place: '7',
    sectionName: 'Терраса',
    date: '10.06.2026',
    time: '20:00',
    guests: 2,
    status: 'Визит состоялся',
    active: false,
    isCancelled: false,
    bookType: 'table',
  },
];

export const DEMO_DISHES: DishData[] = [
  {
    id: 'demo-dish-1',
    name: 'Маргарита',
    weight: '450 г',
    desc: 'Томатный соус, моцарелла, свежий базилик',
    price: '3 500 ₸',
    img: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&q=80',
    category: 'Пицца',
    calories: 850,
    protein: 32,
    fat: 28,
    carbs: 95,
    time: '20 мин',
    tags: [
      { key: 'tag_hit', label: 'Хит', imageUrl: null },
      { key: 'tag_new', label: 'Новинка', imageUrl: null },
    ],
    sizes: [{ sizeId: null, sizeName: 'Стандарт', isDefault: true, price: 3500, portionWeightGrams: 450, energy: 850, modifierGroups: [] }],
    isAvailable: true,
  },
  {
    id: 'demo-dish-2',
    name: 'Пепперони',
    weight: '500 г',
    desc: 'Томатный соус, пепперони, моцарелла',
    price: '4 200 ₸',
    img: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600&q=80',
    category: 'Пицца',
    calories: 980,
    protein: 38,
    fat: 42,
    carbs: 98,
    time: '20 мин',
    tags: [
      { key: 'tag_hit', label: 'Хит', imageUrl: null },
      { key: 'tag_spicy', label: 'Острое', imageUrl: null },
    ],
    sizes: [{ sizeId: null, sizeName: 'Стандарт', isDefault: true, price: 4200, portionWeightGrams: 500, energy: 980, modifierGroups: [] }],
    isAvailable: true,
  },
  {
    id: 'demo-dish-3',
    name: 'Греческий',
    weight: '300 г',
    desc: 'Свежие овощи, брынза, маслины, оливковое масло',
    price: '1 800 ₸',
    img: 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600&q=80',
    category: 'Салаты',
    calories: 320,
    protein: 12,
    fat: 18,
    carbs: 24,
    time: '10 мин',
    tags: [
      { key: 'tag_new', label: 'Новинка', imageUrl: null },
    ],
    sizes: [{ sizeId: null, sizeName: 'Стандарт', isDefault: true, price: 1800, portionWeightGrams: 300, energy: 320, modifierGroups: [] }],
    isAvailable: true,
  },
  {
    id: 'demo-dish-4',
    name: 'Цезарь с курицей',
    weight: '320 г',
    desc: 'Романо, куриное филе, пармезан, крутоны, соус Цезарь',
    price: '2 600 ₸',
    img: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=600&q=80',
    category: 'Салаты',
    calories: 410,
    protein: 28,
    fat: 22,
    carbs: 28,
    time: '10 мин',
    tags: [
      { key: 'tag_hit', label: 'Хит', imageUrl: null },
    ],
    sizes: [{ sizeId: null, sizeName: 'Стандарт', isDefault: true, price: 2600, portionWeightGrams: 320, energy: 410, modifierGroups: [] }],
    isAvailable: true,
  },
  {
    id: 'demo-dish-5',
    name: 'Том Ям',
    weight: '350 г',
    desc: 'Пряный тайский суп с морепродуктами и кокосовым молоком',
    price: '1 990 ₸',
    img: 'https://images.unsplash.com/photo-1547592180-85f173990554?w=600&q=80',
    category: 'Супы',
    calories: 290,
    protein: 22,
    fat: 14,
    carbs: 18,
    time: '15 мин',
    tags: [
      { key: 'tag_spicy', label: 'Острое', imageUrl: null },
      { key: 'tag_new', label: 'Новинка', imageUrl: null },
    ],
    sizes: [{ sizeId: null, sizeName: 'Стандарт', isDefault: true, price: 1990, portionWeightGrams: 350, energy: 290, modifierGroups: [] }],
    isAvailable: true,
  },
  {
    id: 'demo-dish-6',
    name: 'Тирамису',
    weight: '200 г',
    desc: 'Классический итальянский десерт с маскарпоне и кофе',
    price: '1 200 ₸',
    img: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&q=80',
    category: 'Десерты',
    calories: 480,
    protein: 8,
    fat: 24,
    carbs: 56,
    time: '5 мин',
    tags: [
      { key: 'tag_new', label: 'Новинка', imageUrl: null },
    ],
    sizes: [{ sizeId: null, sizeName: 'Стандарт', isDefault: true, price: 1200, portionWeightGrams: 200, energy: 480, modifierGroups: [] }],
    isAvailable: true,
  },
  {
    id: 'demo-dish-7',
    name: 'Кола 0.5л',
    weight: '500 мл',
    desc: 'Coca-Cola',
    price: '500 ₸',
    img: 'https://images.unsplash.com/photo-1625772452859-1c03d884bf80?w=600&q=80',
    category: 'Напитки',
    calories: 210,
    protein: 0,
    fat: 0,
    carbs: 52,
    time: '—',
    tags: [],
    sizes: [{ sizeId: null, sizeName: 'Стандарт', isDefault: true, price: 500, portionWeightGrams: null, energy: 210, modifierGroups: [] }],
    isAvailable: true,
  },
  {
    id: 'demo-dish-8',
    name: 'Свежевыжатый апельсиновый',
    weight: '300 мл',
    desc: 'Натуральный сок из свежих апельсинов',
    price: '1 100 ₸',
    img: 'https://images.unsplash.com/photo-1600271886742-f049cd451bba?w=600&q=80',
    category: 'Напитки',
    calories: 140,
    protein: 2,
    fat: 0,
    carbs: 32,
    time: '5 мин',
    tags: [],
    sizes: [{ sizeId: null, sizeName: 'Стандарт', isDefault: true, price: 1100, portionWeightGrams: null, energy: 140, modifierGroups: [] }],
    isAvailable: true,
  },
];
